/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Kyo */

#ifndef _Included_Kyo
#define _Included_Kyo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Kyo
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Kyo_init
  (JNIEnv *, jclass);

/*
 * Class:     Kyo
 * Method:    key
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Kyo_key
  (JNIEnv *, jclass);

/*
 * Class:     Kyo
 * Method:    exit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Kyo_exit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
